version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 12
                - 10
                - 8
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build
        - test